metadata:
  title: Разработка кроссплатформенных программных систем
  subtitle: Учебно-методическое пособие
  author: П.Н. Советов, А.В. Горчаков
  date: Москва – 2025
  toc-title: Оглавление
  bibliography: bibliography.bib
  link-citations: true
  csl: gost-r-7-0-5-2008-numeric-iaa.csl
